import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';

const pretendard = localFont({
  src: './fonts/pretendard/PretendardVariable.woff2',
  display: 'swap',
  weight: '100 900',
  variable: '--font-pretendard',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko" className={pretendard.variable}>
      <body className="bg-[#F2F2F2]">
          {/* 앱 프레임: 화면을 넘지 않게 고정 */}
          <div className="mx-auto flex min-h-dvh w-full max-w-[420px] flex-col bg-white md:max-w-[500px] lg:max-w-[640px]">
            {children}
          </div>
      </body>
    </html>
  );
}
